/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import auctions.AuctionClientFact;
import auctions.objects.Auction;
import auctions.objects.Auctions;
import auctions.objects.AuctionClient;
import controller.ClientController;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author alexander
 */
public class ClientGUI extends javax.swing.JFrame {
    
    private static DefaultListModel<String> lstYourAuctionsModel;
    private static DefaultListModel<String> lstFollowedAuctionsModel;
    private static DefaultListModel<String> lstAvailableAuctionsModel;
    
    private static String nombre;
    
    private final AuctionClient client;
    private final Auctions auctions;
    private final Auctions followedAuctions;
    
    private ClientController controller;

    /**
     * Creates new form OferenteFrame
     */
    public ClientGUI() {
        initComponents();
        
        do {
            nombre = JOptionPane.showInputDialog(this, "Introduzca su nombre", "Nombre", JOptionPane.PLAIN_MESSAGE);
        } while ("".equals(nombre));
            
        client = AuctionClientFact.createClient(nombre);
            
        auctions = new Auctions();
        followedAuctions = new Auctions();
            
        lstYourAuctions.removeAll();
        lstYourAuctionsModel = new DefaultListModel<>();
        lstYourAuctions.setModel(lstYourAuctionsModel);
        
        lstFollowedAuctions.removeAll();
        lstAvailableAuctions.removeAll();
        lstFollowedAuctionsModel = new DefaultListModel<>();
        lstFollowedAuctions.setModel(lstFollowedAuctionsModel);
        lstAvailableAuctionsModel = new DefaultListModel<>();
        lstAvailableAuctions.setModel(lstAvailableAuctionsModel);
            
        SpinnerModel spnSiguientePrecioModel = new SpinnerNumberModel(0.0,0.0,Double.MAX_VALUE, 0.1);
        spnNextPrice.setModel(spnSiguientePrecioModel);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jspSubastas = new javax.swing.JScrollPane();
        lstAvailableAuctions = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnFollowAuction = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstFollowedAuctions = new javax.swing.JList<>();
        txtActualPrice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtNextPrice = new javax.swing.JTextField();
        btnUnfollowAuction = new javax.swing.JToggleButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMessagesFromServer = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        btnMakeNewOffer = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtUpdate = new javax.swing.JButton();
        lblAuctionImage = new javax.swing.JLabel();
        lblProductImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstYourAuctions = new javax.swing.JList<>();
        txtYourAuctionId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtYourAuctionStatus = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtYourAuctionBestOffer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtYourAuctionsUserBestOffer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtYourAuctionsNewOffer = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtYourAuctionsUserNewOffer = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        spnNextPrice = new javax.swing.JSpinner();
        btnAcceptNewOffer = new javax.swing.JButton();
        btnSendMessageToWinner = new javax.swing.JButton();
        btnCancelAuction = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtAuctionEndTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtYourAuctionsIdProduct = new javax.swing.JTextField();
        lblYourAuctionsAuctionImage = new javax.swing.JLabel();
        lblYourAuctionsProductImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtMessageToWinner = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNewAuctionid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnnewAuctionYear = new javax.swing.JSpinner();
        spnnewAuctionMonth = new javax.swing.JSpinner();
        spnNewAuctionDay = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spnNewAuctionDuration = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        btnCreateNewAuction = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        spnNewAuctionHour = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        txtNewAuctionProductName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNewAuctionDescription = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        txtnewAuctionInitialPrice = new javax.swing.JTextField();
        lblnewAuctionAuctionImage = new javax.swing.JLabel();
        lblNewProductImage = new javax.swing.JLabel();
        lblMensajeError = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        lstAvailableAuctions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAvailableAuctions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAvailableAuctionsValueChanged(evt);
            }
        });
        jspSubastas.setViewportView(lstAvailableAuctions);

        jLabel24.setText("Subastas disponibles:");

        jLabel25.setText("Precio actual:");

        jLabel26.setText("Subastas seguidas:");

        btnFollowAuction.setText("=>");
        btnFollowAuction.setEnabled(false);
        btnFollowAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFollowAuctionActionPerformed(evt);
            }
        });

        lstFollowedAuctions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstFollowedAuctions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstFollowedAuctionsMouseClicked(evt);
            }
        });
        lstFollowedAuctions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFollowedAuctionsValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstFollowedAuctions);

        txtActualPrice.setEditable(false);

        jLabel27.setText("Precio siguiente:");

        txtNextPrice.setEditable(false);

        btnUnfollowAuction.setText("<=");
        btnUnfollowAuction.setEnabled(false);
        btnUnfollowAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnfollowAuctionActionPerformed(evt);
            }
        });

        jLabel28.setText("Mensajes:");

        txtMessagesFromServer.setEditable(false);
        txtMessagesFromServer.setColumns(20);
        txtMessagesFromServer.setLineWrap(true);
        txtMessagesFromServer.setRows(5);
        jScrollPane5.setViewportView(txtMessagesFromServer);

        jLabel29.setText("Producto");

        txtProductId.setEditable(false);

        btnMakeNewOffer.setText("Ofertar");
        btnMakeNewOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeNewOfferActionPerformed(evt);
            }
        });

        jLabel30.setText("Estado: ");

        txtUpdate.setText("Actualizar");
        txtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateActionPerformed(evt);
            }
        });

        lblAuctionImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuctionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblAuctionImage.setText("Auction Image");
        lblAuctionImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblAuctionImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblProductImage.setText("Product Image");
        lblProductImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblProductImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jspSubastas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFollowAuction)
                            .addComponent(btnUnfollowAuction))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(txtProductId))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtState))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtActualPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnMakeNewOffer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblAuctionImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnFollowAuction)
                                .addGap(18, 18, 18)
                                .addComponent(btnUnfollowAuction)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jspSubastas)
                                .addGap(18, 18, 18)))
                        .addComponent(txtUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(txtProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtActualPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtNextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuctionImage, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(lblProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnMakeNewOffer)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Subastas", jPanel3);

        jLabel1.setText("Id:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tus subastas");

        lstYourAuctions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstYourAuctionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstYourAuctions);

        txtYourAuctionId.setEditable(false);

        jLabel11.setText("Status: ");

        txtYourAuctionStatus.setEditable(false);

        jLabel12.setText("Mejor oferta hasta ahora: ");

        txtYourAuctionBestOffer.setEditable(false);

        jLabel13.setText("Usuario: ");

        txtYourAuctionsUserBestOffer.setEditable(false);

        jLabel14.setText("Nueva oferta: ");

        txtYourAuctionsNewOffer.setEditable(false);

        jLabel15.setText("Usuario: ");

        txtYourAuctionsUserNewOffer.setEditable(false);

        jLabel16.setText("Definir siguiente precio: ");

        btnAcceptNewOffer.setText("Aceptar nueva oferta");
        btnAcceptNewOffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptNewOfferActionPerformed(evt);
            }
        });

        btnSendMessageToWinner.setText("Enviar mensaje al ganador");
        btnSendMessageToWinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageToWinnerActionPerformed(evt);
            }
        });

        btnCancelAuction.setText("Cancela la subasta");
        btnCancelAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAuctionActionPerformed(evt);
            }
        });

        jLabel18.setText("Tiempo para finalizar la subasta: ");

        txtAuctionEndTime.setEditable(false);

        jLabel19.setText("horas");

        jLabel23.setText("Id del producto: ");

        txtYourAuctionsIdProduct.setEditable(false);

        lblYourAuctionsAuctionImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourAuctionsAuctionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblYourAuctionsAuctionImage.setText("Auction Image");
        lblYourAuctionsAuctionImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblYourAuctionsAuctionImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblYourAuctionsProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourAuctionsProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblYourAuctionsProductImage.setText("Product Image");
        lblYourAuctionsProductImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblYourAuctionsProductImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        txtMessageToWinner.setColumns(20);
        txtMessageToWinner.setRows(5);
        jScrollPane6.setViewportView(txtMessageToWinner);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txtAuctionEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAcceptNewOffer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtYourAuctionsIdProduct))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtYourAuctionsUserBestOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtYourAuctionsNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtYourAuctionsUserNewOffer))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtYourAuctionBestOffer)))
                                    .addComponent(jLabel16))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spnNextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtYourAuctionId, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtYourAuctionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSendMessageToWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblYourAuctionsAuctionImage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblYourAuctionsProductImage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(txtAuctionEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtYourAuctionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtYourAuctionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtYourAuctionBestOffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtYourAuctionsUserBestOffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtYourAuctionsNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblYourAuctionsAuctionImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblYourAuctionsProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtYourAuctionsUserNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(txtYourAuctionsIdProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnNextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelAuction)
                            .addComponent(btnSendMessageToWinner)
                            .addComponent(btnAcceptNewOffer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );

        jTabbedPane1.addTab("Tus subastas", jPanel1);

        jLabel3.setText("Id de la subasta: ");

        jLabel5.setText("Fecha de inicio: ");

        jLabel6.setText("Día: ");

        jLabel7.setText("Mes: ");

        jLabel8.setText("Año: ");

        jLabel9.setText("Duración: ");

        jLabel10.setText("horas");

        btnCreateNewAuction.setText("Crear la nueva subasta");
        btnCreateNewAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewAuctionActionPerformed(evt);
            }
        });

        jLabel20.setText("Hora:");

        jLabel21.setText("Nombre del producto: ");

        jLabel4.setText("Descripción: ");

        txtNewAuctionDescription.setColumns(20);
        txtNewAuctionDescription.setRows(5);
        jScrollPane2.setViewportView(txtNewAuctionDescription);

        jLabel22.setText("Precio inicial: ");

        lblnewAuctionAuctionImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnewAuctionAuctionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblnewAuctionAuctionImage.setText("Auction Image");
        lblnewAuctionAuctionImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblnewAuctionAuctionImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNewProductImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/head64.png"))); // NOI18N
        lblNewProductImage.setText("Product Image");
        lblNewProductImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNewProductImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCreateNewAuction)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNewAuctionid))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNewAuctionProductName))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnNewAuctionDay, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnnewAuctionMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnnewAuctionYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnNewAuctionHour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnNewAuctionDuration)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(txtnewAuctionInitialPrice))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnewAuctionAuctionImage, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(lblNewProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNewAuctionid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spnNewAuctionDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(spnnewAuctionMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(spnnewAuctionYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(spnNewAuctionHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spnNewAuctionDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewAuctionProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtnewAuctionInitialPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addComponent(lblnewAuctionAuctionImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateNewAuction))
                    .addComponent(lblNewProductImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear subasta", jPanel2);

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalir);

        jMenuBar2.add(mnuArchivo);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(lblMensajeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeError))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tpSubastas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendMessageToWinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageToWinnerActionPerformed
        // TODO add your handling code here:
        
        int pos = lstYourAuctions.getSelectedIndex();
        
        if (pos != -1) {
            Auction auction = auctions.get(lstYourAuctions.getSelectedValue());
            if (auction != null) {
                if (!"".equals(auction.getBidderId())) {
                    String idAuction = auction.getId();
                    String winner = auction.getBidderId();
                    String message = txtMessageToWinner.getText();
                    txtMessageToWinner.setText("");
                    controller.auctionFinished(idAuction, winner, message);
                }
            }
        } else {
            printError("No hay una subasta seleccionada.");
        }
        
    }//GEN-LAST:event_btnSendMessageToWinnerActionPerformed

    private void btnCreateNewAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewAuctionActionPerformed
        // TODO add your handling code here:
        try{
            if (!"".equals(txtNewAuctionid.getText()) && 
                    !"".equals(txtNewAuctionProductName.getText()) &&
                    !"".equals(txtNewAuctionDescription.getText()) &&
                    !"".equals(txtnewAuctionInitialPrice.getText())) {
                String AuctionName = txtNewAuctionid.getText();
                int dia = (int)spnNewAuctionDay.getValue();
                int mes = (int)spnnewAuctionMonth.getValue();
                int anno = (int)spnnewAuctionYear.getValue();
                int hora = (int)spnNewAuctionHour.getValue();
                int duracion = (int)spnNewAuctionDuration.getValue();
                String nombreProduct = txtNewAuctionProductName.getText();
                String descripcion = txtNewAuctionDescription.getText();
                double initialPrice = Double.parseDouble(txtnewAuctionInitialPrice.getText());
                Icon auctionImage = lblAuctionImage.getIcon();
                Icon productImage = lblProductImage.getIcon();
                
                Date fecha = new Date(anno, mes, dia, hora, 0);
                
                print("Enviando la solicitud de agregar la nueva subasta");
                controller.addAuction(AuctionName, fecha, duracion, nombreProduct, descripcion, productImage, initialPrice, initialPrice, auctionImage);
            } else {
                printError("Falta algún dato para la subasta.");
            }
        } catch(NumberFormatException ex) {
            printError("Revise que todos los números sean válidos.");
        }
    }//GEN-LAST:event_btnCreateNewAuctionActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        
        controller.closeConnection();
        print("Cerrando el programa...");
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void lstYourAuctionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstYourAuctionsValueChanged
        // TODO add your handling code here:
        
        String selectedValue = lstYourAuctions.getSelectedValue();
        
        if (selectedValue != null && !"".equals(selectedValue)) {
            Auction auction = auctions.get(selectedValue);
            
            actualizarTextos(auction);
        }
    }//GEN-LAST:event_lstYourAuctionsValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        controller.closeConnection();
        print("Cerrando el programa...");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btnAcceptNewOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptNewOfferActionPerformed
        // TODO add your handling code here:
        
        int pos = lstYourAuctions.getSelectedIndex();
        
        if (pos != -1) {
            String selectedValue = lstYourAuctions.getSelectedValue();
            
            Auction auction = auctions.get(selectedValue);
            
            double newPrice = (double)spnNextPrice.getValue();
            String newBidder = auction.getNewBidderId();
            
            auction.setNextPrice(auction.getNextPrice());
            auction.setBidderId(auction.getNewBidderId());
            auction.setNextPrice(newPrice);
            auction.setNewBidder(null);
            auctions.add(auction);
            
            controller.acceptOffer(selectedValue, newBidder, newPrice);
            actualizarTextos(auction);
        } else {
            print("Debe seleccionar alguna subasta.");
        }
    }//GEN-LAST:event_btnAcceptNewOfferActionPerformed

    private void btnCancelAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAuctionActionPerformed
        // TODO add your handling code here:
        
        int pos = lstYourAuctions.getSelectedIndex();
        
        if (pos != -1) {
            String selectedValue = lstYourAuctions.getSelectedValue();
            
            Auction auction = auctions.get(selectedValue);
            
            auction.setState(Auction.STATE.CANCELED);
            
            auctions.add(auction);
            
            controller.cancelAuction(selectedValue);
            actualizarTextos(auction);
        } else {
            print("Debe seleccionar alguna subasta.");
        }
    }//GEN-LAST:event_btnCancelAuctionActionPerformed

    private void lstAvailableAuctionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAvailableAuctionsValueChanged
        // TODO add your handling code here:

        if (lstAvailableAuctions.isSelectionEmpty()) {
            btnFollowAuction.setEnabled(false);
        } else {
            btnFollowAuction.setEnabled(true);
        }
    }//GEN-LAST:event_lstAvailableAuctionsValueChanged

    private void btnFollowAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFollowAuctionActionPerformed
        // TODO add your handling code here:

        int pos = lstAvailableAuctions.getSelectedIndex();
        if (pos != -1) {
            String AuctionName = lstAvailableAuctions.getSelectedValue();

            print("Solicitando seguir la subasta " + AuctionName + ".");
            controller.followAuction(AuctionName);
        } else {
            printError("Se debe escoger una subasta.");
        }
    }//GEN-LAST:event_btnFollowAuctionActionPerformed

    private void lstFollowedAuctionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstFollowedAuctionsMouseClicked
        // TODO add your handling code here:
        AuctionSelected();
    }//GEN-LAST:event_lstFollowedAuctionsMouseClicked

    
    private void lstFollowedAuctionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFollowedAuctionsValueChanged
        // TODO add your handling code here:
        if (lstFollowedAuctions.getSelectedIndex() != -1) {
            btnUnfollowAuction.setEnabled(true);
        } else {
            btnUnfollowAuction.setEnabled(false);
        }
        AuctionSelected();
    }//GEN-LAST:event_lstFollowedAuctionsValueChanged

    private void btnUnfollowAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnfollowAuctionActionPerformed
        // TODO add your handling code here:

        int pos = lstFollowedAuctions.getSelectedIndex();
        if (pos != -1) {
            String AuctionName = lstFollowedAuctions.getSelectedValue();

            System.out.println("Solicitud de dejar de seguir la subasta" + AuctionName + ".");
            controller.unfollowAuction(AuctionName);
            if (pos >= 0 && pos < lstFollowedAuctionsModel.size()){
                lstAvailableAuctionsModel.addElement(lstAvailableAuctionsModel.remove(pos));
            }
        } else {
            printError("Se debe escoger una subasta.");
        }
    }//GEN-LAST:event_btnUnfollowAuctionActionPerformed

    private void btnMakeNewOfferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeNewOfferActionPerformed
        // TODO add your handling code here:
        int escogido = lstFollowedAuctions.getSelectedIndex();
        if (escogido != -1) {
            Auction auction = followedAuctions.get(lstFollowedAuctions.getSelectedValue());
            if (auction.getState() == Auction.STATE.IN_PROGRESS) {
                controller.newOffer(auction.getId(), auction.getNextPrice());
            }
        } else {
            printError("Se debe escoger una subasta para ofertar.");
        }
    }//GEN-LAST:event_btnMakeNewOfferActionPerformed

    private void txtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateActionPerformed
        // TODO add your handling code here:
        controller.sendAllAuctions();
        lstAvailableAuctionsModel.clear();
        lstFollowedAuctionsModel.clear();
        lstYourAuctionsModel.clear();
    }//GEN-LAST:event_txtUpdateActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptNewOffer;
    private javax.swing.JButton btnCancelAuction;
    private javax.swing.JButton btnCreateNewAuction;
    private javax.swing.JButton btnFollowAuction;
    private javax.swing.JButton btnMakeNewOffer;
    private javax.swing.JButton btnSendMessageToWinner;
    private javax.swing.JToggleButton btnUnfollowAuction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane jspSubastas;
    private javax.swing.JLabel lblAuctionImage;
    private javax.swing.JLabel lblMensajeError;
    private javax.swing.JLabel lblNewProductImage;
    private javax.swing.JLabel lblProductImage;
    private javax.swing.JLabel lblYourAuctionsAuctionImage;
    private javax.swing.JLabel lblYourAuctionsProductImage;
    private javax.swing.JLabel lblnewAuctionAuctionImage;
    private javax.swing.JList<String> lstAvailableAuctions;
    private javax.swing.JList<String> lstFollowedAuctions;
    private javax.swing.JList<String> lstYourAuctions;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JSpinner spnNewAuctionDay;
    private javax.swing.JSpinner spnNewAuctionDuration;
    private javax.swing.JSpinner spnNewAuctionHour;
    private javax.swing.JSpinner spnNextPrice;
    private javax.swing.JSpinner spnnewAuctionMonth;
    private javax.swing.JSpinner spnnewAuctionYear;
    private javax.swing.JTextField txtActualPrice;
    private javax.swing.JTextField txtAuctionEndTime;
    private javax.swing.JTextArea txtMessageToWinner;
    private javax.swing.JTextArea txtMessagesFromServer;
    private javax.swing.JTextArea txtNewAuctionDescription;
    private javax.swing.JTextField txtNewAuctionProductName;
    private javax.swing.JTextField txtNewAuctionid;
    private javax.swing.JTextField txtNextPrice;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtState;
    private javax.swing.JButton txtUpdate;
    private javax.swing.JTextField txtYourAuctionBestOffer;
    private javax.swing.JTextField txtYourAuctionId;
    private javax.swing.JTextField txtYourAuctionStatus;
    private javax.swing.JTextField txtYourAuctionsIdProduct;
    private javax.swing.JTextField txtYourAuctionsNewOffer;
    private javax.swing.JTextField txtYourAuctionsUserBestOffer;
    private javax.swing.JTextField txtYourAuctionsUserNewOffer;
    private javax.swing.JTextField txtnewAuctionInitialPrice;
    // End of variables declaration//GEN-END:variables

    public void actualizarTextos (Auction auction) {
        txtYourAuctionId.setText(auction.getId());
        txtYourAuctionStatus.setText(auction.getState().toString());
        txtYourAuctionBestOffer.setText(Double.toString(auction.getActualPrice()));
        txtYourAuctionsNewOffer.setText(Double.toString(auction.getNextPrice()));
        txtYourAuctionsIdProduct.setText(auction.getProduct().getId());
        spnNextPrice.setValue(auction.getNextPrice());
        if (!"".equals(auction.getBidderId())) {
            txtYourAuctionsUserBestOffer.setText(auction.getBidderId());
        } else {
            txtYourAuctionsUserBestOffer.setText("");
        }
        if ("".equals(auction.getNewBidderId())) {
            txtYourAuctionsUserNewOffer.setText(auction.getNewBidderId());
        } else {
            txtYourAuctionsUserNewOffer.setText("");
        }
    }

    public void setController(ClientController controller) {
        this.controller = controller;
    }
    
    public void AuctionSelected() {
        String subasta = lstFollowedAuctions.getSelectedValue();
        if (auctions.containsKey(subasta)) {
            Auction auction = auctions.get(subasta);
            actualizarTextos(auction);
        }
    }

    public AuctionClient getClient() {
        return client;
    }
    
    public void newOffer(String auctionId, String bidderId, double nextPrice) {
        Auction auction = auctions.get(auctionId);
        if (nextPrice == auction.getNextPrice() && !"".equals(auction.getNewBidderId())) {
            auction.setNewBidder(bidderId);
        }
    }
    
    public void offerAccepted(String auctionId, String bidderId, double newPrice) {
        Auction auction = auctions.get(auctionId);
        auction.setBidderId(bidderId);
        auction.setActualPrice(newPrice);
    }
    
    public void deleteAllAuctions() {
        lstAvailableAuctionsModel.clear();
        lstYourAuctionsModel.clear();
    }
    
    public void addAuction(Auction auction) {
        auctions.add(auction);
        lstAvailableAuctionsModel.addElement(auction.getId());
        if (client.getId().equals(auction.getAuctioneerId())) {
            lstYourAuctionsModel.addElement(auction.getId());
        }
    }
    
    public void auctionFinished(String auctionId) {
        auctions.get(auctionId).setState(Auction.STATE.FINISHED);
    }

    public void print(String message) {
        txtMessagesFromServer.setText(txtMessagesFromServer.getText() + '\n' + message);
    }

    public void printError(String message) {
        txtMessagesFromServer.setText(txtMessagesFromServer.getText() + '\n' + "ERROR: " + message);
    }
    
}
