/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.LinkedList;
import model.patterns.observer.IObservable;
import model.patterns.observer.IObserver;

/**
 *
 * @author aborbon
 */
public class Server extends javax.swing.JFrame implements IObservable {
    // Lista de observers
    private final LinkedList<IObserver> observers;

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        
        //Inicializa la lista de observers
        observers = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMessages.setColumns(20);
        txtMessages.setRows(5);
        jScrollPane1.setViewportView(txtMessages);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Imprime un mensaje en la pantalla
     * @param message Mensaje que se desea imprimir
     */
    public void print(String message) {
        txtMessages.append(message + '\n');
    }
    
    @Override
    public void addObserver(IObserver observer) {
        observers.add(observer);
    }

    @Override
    public void removeObserver(IObserver observer) {
        observers.remove(observer);
    }

    @Override
    public void update(IObserver observer, Object message) {}

    @Override
    public void updateAll(Object message) {
        for (IObserver observer : observers) {
            observer.update(message);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables
}
